name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  json_annotation: ^1.0.0
  http: any
  shared_preferences: any
  #json_to_form: "^0.0.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.10.0
  json_serializable: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/neuro-logo.png
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf